const crypto = require('crypto');
const TTL = 30 * 60 * 1000;
const MAX_GAMES = 1000;
const games = new Map();
const sessions = new Map();
const WORDS = [
  ['javascript', 'Lenguaje muy usado para la web'], ['familia', 'Personas unidas por parentesco o afecto'],
  ['planeta', 'Cuerpo que gira alrededor de una estrella'], ['computadora', 'Máquina electrónica para procesar información'],
  ['montana', 'Elevación natural del terreno'], ['aventura', 'Experiencia emocionante o arriesgada'],
  ['elefante', 'Animal terrestre de gran tamaño'], ['biblioteca', 'Lugar donde se conservan libros'],
  ['programador', 'Persona que escribe código'], ['oceano', 'Gran extensión de agua salada']
];
const QUIZ = [
  { question: '¿Cuál es el planeta más cercano al Sol?', options: ['Venus', 'Mercurio', 'Marte', 'Júpiter'], answer: 1 },
  { question: '¿Cuántos lados tiene un hexágono?', options: ['5', '6', '7', '8'], answer: 1 },
  { question: '¿Cuál es el océano más grande?', options: ['Atlántico', 'Índico', 'Pacífico', 'Ártico'], answer: 2 },
  { question: '¿Qué lenguaje se ejecuta directamente en el navegador?', options: ['JavaScript', 'Python', 'C++', 'Rust'], answer: 0 },
  { question: '¿Cuántos minutos tiene una hora?', options: ['30', '45', '60', '90'], answer: 2 }
];
function ownerKey(owner, type) { return `${type}:${crypto.createHash('sha256').update(String(owner || 'anonymous')).digest('hex')}`; }
function cleanup() { const now = Date.now(); for (const [id, g] of games) if (g.expiresAt <= now) games.delete(id); for (const [key, id] of sessions) if (!games.has(id)) sessions.delete(key); }
function create(type, data, owner) { cleanup(); if (games.size >= MAX_GAMES) games.delete(games.keys().next().value); const id = crypto.randomBytes(9).toString('hex'); const sessionOwner = owner || 'anonymous'; games.set(id, { type, data, owner: String(sessionOwner), expiresAt: Date.now() + TTL }); sessions.set(ownerKey(sessionOwner, type), id); return id; }
function get(id, type) { const key = String(id || ''); const g = games.get(key); if (!g || g.type !== type || g.expiresAt <= Date.now()) { if (g) games.delete(key); return null; } g.expiresAt = Date.now() + TTL; return g; }
function getSession(owner, type) { const id = sessions.get(ownerKey(owner, type)); return id ? get(id, type) : null; }
function remove(id) { const g = games.get(String(id)); if (g) sessions.delete(ownerKey(g.owner, g.type)); games.delete(String(id)); }
function stateHangman(data) { const set = new Set(data.guessed); const masked = [...data.word].map(c => set.has(c) ? c : '_').join(' '); const won = [...data.word].every(c => set.has(c)); const lost = data.wrong >= data.maxWrong; return { masked, guessed: data.guessed, wrong: data.wrong, maxWrong: data.maxWrong, status: won ? 'won' : lost ? 'lost' : 'playing', word: won || lost ? data.word : undefined }; }
function newHangman(owner) { const [word, hint] = WORDS[Math.floor(Math.random()*WORDS.length)]; const data={word,hint,guessed:[],wrong:0,maxWrong:6}; const id=create('hangman',data,owner); return { id, hint, ...stateHangman(data) }; }
function hangmanGuess(id, value, owner) { const g=get(id,'hangman') || getSession(owner,'hangman'); if(!g)return {error:'Partida no encontrada o expirada. Genera una nueva partida primero.'}; const guess=String(value||'').trim().toLowerCase(); if(!/^[a-záéíóúüñ]$/.test(guess))return{error:'Debes enviar una sola letra.'}; if(g.data.guessed.includes(guess))return{error:'Ya probaste esa letra.',...stateHangman(g.data),id:g.id}; g.data.guessed.push(guess); if(!g.data.word.includes(guess))g.data.wrong++; const out=stateHangman(g.data); if(out.status!=='playing')remove(g.id); else out.id=g.id; return out; }
function newGuess(owner){const number=Math.floor(Math.random()*100)+1;const id=create('guess',{number,attempts:0,maxAttempts:7},owner);return{id,min:1,max:100,attempts:0,maxAttempts:7,status:'playing',message:'Partida creada. Usa el mismo API Key para enviar tus intentos.'};}
function guessNumber(id,value,owner){const g=get(id,'guess')||getSession(owner,'guess');if(!g)return{error:'Partida no encontrada o expirada. Genera una nueva partida primero.'};const n=Number(value);if(!Number.isInteger(n)||n<1||n>100)return{error:'El número debe ser un entero entre 1 y 100.'};g.data.attempts++;if(n===g.data.number||g.data.attempts>=g.data.maxAttempts){const won=n===g.data.number;remove(g.id);return{status:won?'won':'lost',attempts:g.data.attempts,number:won?undefined:g.data.number,message:won?'¡Correcto!':'Se acabaron los intentos.'};}return{id:g.id,status:'playing',hint:n<g.data.number?'El número secreto es mayor.':'El número secreto es menor.',attempts:g.data.attempts,remaining:g.data.maxAttempts-g.data.attempts};}
function newScramble(owner){const[word]=WORDS[Math.floor(Math.random()*WORDS.length)];let scrambled=word;for(let i=0;i<10&&scrambled===word;i++)scrambled=[...word].sort(()=>Math.random()-.5).join('');const id=create('scramble',{word,attempts:0},owner);return{id,scrambled,length:word.length,status:'playing'};}
function scrambleGuess(id,value,owner){const g=get(id,'scramble')||getSession(owner,'scramble');if(!g)return{error:'Partida no encontrada o expirada. Genera una nueva partida primero.'};g.data.attempts++;const won=String(value||'').trim().toLowerCase()===g.data.word;if(won)remove(g.id);return won?{status:'won',attempts:g.data.attempts,word:g.data.word,message:'¡Palabra correcta!'}:{id:g.id,status:'playing',attempts:g.data.attempts,message:'Incorrecto, inténtalo de nuevo.'};}
function newWord(owner){const[word,hint]=WORDS[Math.floor(Math.random()*WORDS.length)];const id=create('word',{word,hint},owner);return{id,hint,length:word.length,firstLetter:word[0],status:'playing'};}
function wordGuess(id,value,owner){const g=get(id,'word')||getSession(owner,'word');if(!g)return{error:'Partida no encontrada o expirada. Genera una nueva partida primero.'};if(String(value||'').trim().toLowerCase()===g.data.word){remove(g.id);return{status:'won',word:g.data.word,message:'¡Correcto!'};}return{id:g.id,status:'playing',message:'No es esa palabra. Sigue intentando.'};}
function newQuiz(owner){const question=QUIZ[Math.floor(Math.random()*QUIZ.length)];const id=create('quiz',{question},owner);return{id,question:question.question,options:question.options,status:'playing'};}
function quizAnswer(id,value,owner){const g=get(id,'quiz')||getSession(owner,'quiz');if(!g)return{error:'Pregunta no encontrada o expirada. Genera una nueva pregunta primero.'};const a=Number(value);if(!Number.isInteger(a)||a<0||a>=g.data.question.options.length)return{error:'answer debe ser un índice válido.'};const correct=a===g.data.question.answer;remove(g.id);return{status:correct?'won':'lost',correct,answer:a,correctAnswer:g.data.question.answer,message:correct?'¡Respuesta correcta!':'Respuesta incorrecta.'};}
function battle(name='Jugador'){const enemies=['Dragón','Robot','Ninja','Pirata','Mago','Guardián'];const make=n=>({name:n,attack:40+Math.floor(Math.random()*61),defense:40+Math.floor(Math.random()*61),speed:40+Math.floor(Math.random()*61)});const player=make(String(name).trim().slice(0,30)||'Jugador'),opponent=make(enemies[Math.floor(Math.random()*enemies.length)]);const score=x=>x.attack+x.defense+x.speed,ps=score(player),os=score(opponent);return{status:'finished',player,opponent,scores:{player:ps,opponent:os},winner:ps===os?'draw':ps>os?'player':'opponent'};}
function memory(owner){const sequence=Array.from({length:5},()=>Math.floor(Math.random()*10));const id=create('memory',{sequence},owner);return{id,length:sequence.length,sequence,status:'memorize'};}
function memoryCheck(id,value,owner){const g=get(id,'memory')||getSession(owner,'memory');if(!g)return{error:'Partida no encontrada o expirada. Genera una nueva partida primero.'};if(!Array.isArray(value)||value.length!==g.data.sequence.length)return{error:'Envía la secuencia completa como array.'};const correct=value.every((n,i)=>Number(n)===g.data.sequence[i]);remove(g.id);return{status:correct?'won':'lost',correct,sequence:g.data.sequence};}
module.exports={newHangman,hangmanGuess,newGuess,guessNumber,newScramble,scrambleGuess,newWord,wordGuess,newQuiz,quizAnswer,battle,memory,memoryCheck};
