const express = require('express');
const router = express.Router();

const quotes = [
    "Nunca es tarde para empezar de nuevo.",
    "Los pequeños pasos también te llevan lejos.",
    "Cree en ti, incluso cuando nadie más lo haga.",
    "Todo gran logro comienza con una decisión.",
    "No te rindas; lo mejor puede estar por llegar.",
    "A veces perderse es la mejor forma de encontrarse.",
    "Haz hoy algo que tu yo del futuro agradezca.",
    "La paciencia también es una forma de valentía.",
    "No necesitas ser perfecto para avanzar.",
    "Cada día es una nueva oportunidad.",
    "Si puedes soñarlo, puedes trabajar para conseguirlo.",
    "Los errores no te definen, te enseñan.",
    "Tu esfuerzo de hoy construye tu mañana.",
    "Nunca subestimes lo que puedes lograr con constancia.",
    "La confianza se construye paso a paso.",
    "Donde termina el miedo, comienza la aventura.",
    "No compares tu camino con el de los demás.",
    "A veces avanzar lentamente sigue siendo avanzar.",
    "Hazlo con miedo, pero hazlo.",
    "Tu historia todavía tiene muchos capítulos por escribir.",
    "El éxito comienza cuando decides intentarlo.",
    "No dejes que un mal día te haga pensar que tienes una mala vida.",
    "Cada caída es una oportunidad para levantarte más fuerte.",
    "La disciplina te llevará donde la motivación no puede.",
    "Tu futuro depende de lo que hagas hoy.",
    "El tiempo que inviertes en ti nunca es tiempo perdido.",
    "Sé paciente contigo mismo.",
    "Las grandes cosas toman tiempo.",
    "Nunca sabes lo cerca que estás de conseguirlo.",
    "Un día difícil no significa una vida difícil.",
    "Tu valor no depende de la opinión de los demás.",
    "Aprende a disfrutar el proceso.",
    "La constancia vence al talento cuando el talento no se esfuerza.",
    "No tengas miedo de cambiar de camino.",
    "Lo que hoy parece imposible mañana puede ser realidad.",
    "Tu mejor versión se construye todos los días.",
    "No necesitas tenerlo todo resuelto para comenzar.",
    "El primer paso siempre es el más importante.",
    "Confía en el proceso.",
    "El fracaso también forma parte del éxito.",
    "Nunca abandones algo que realmente quieres.",
    "Tu esfuerzo silencioso algún día hablará por ti.",
    "Haz que cada día cuente.",
    "La vida cambia cuando cambias tu forma de verla.",
    "El miedo es una señal, no una sentencia.",
    "Rodéate de personas que crean en tus sueños.",
    "No permitas que tus dudas sean más grandes que tus sueños.",
    "Cada amanecer trae una nueva oportunidad.",
    "La felicidad también se encuentra en las cosas pequeñas.",
    "No esperes el momento perfecto; crea el momento.",
    "Tu camino es único, respétalo.",
    "El progreso es progreso, aunque sea pequeño.",
    "A veces descansar también es avanzar.",
    "Nunca es demasiado tarde para aprender.",
    "El conocimiento abre puertas que antes parecían cerradas.",
    "La humildad también es una forma de grandeza.",
    "Sé la razón por la que alguien vuelva a creer en la bondad.",
    "Una sonrisa puede cambiar un día entero.",
    "Haz el bien sin esperar nada a cambio.",
    "La bondad nunca pasa de moda.",
    "Las palabras pueden cambiar vidas.",
    "Escuchar también es una forma de amar.",
    "Cuida a quienes siempre están contigo.",
    "Valora lo que tienes mientras trabajas por lo que quieres.",
    "La gratitud transforma lo que tienes en suficiente.",
    "No necesitas mucho para ser feliz.",
    "La paz vale más que cualquier discusión.",
    "Aprende a dejar ir lo que ya no te hace bien.",
    "Cerrar una puerta también puede abrir otra.",
    "A veces perder algo es ganar libertad.",
    "No todo lo que termina es un fracaso.",
    "Algunas despedidas son nuevos comienzos.",
    "El pasado enseña, pero no debe controlar tu futuro.",
    "No puedes cambiar ayer, pero sí puedes cambiar mañana.",
    "Cada experiencia deja una enseñanza.",
    "Las heridas también pueden convertirse en fuerza.",
    "Con el tiempo, muchas cosas encuentran su lugar.",
    "Todo pasa, incluso los momentos difíciles.",
    "Después de la tormenta siempre llega la calma.",
    "La esperanza aparece incluso en los días más oscuros.",
    "Nunca pierdas la esperanza.",
    "Mientras haya vida, hay posibilidades.",
    "Siempre existe una razón para seguir.",
    "Un nuevo día puede cambiarlo todo.",
    "No sabes qué sorpresas tiene preparada la vida.",
    "El futuro puede ser mucho mejor de lo que imaginas.",
    "Atrévete a imaginar algo diferente.",
    "Los sueños necesitan acción para convertirse en realidad.",
    "Soñar es el comienzo, actuar es el camino.",
    "No construyas límites donde debería haber oportunidades.",
    "Tu imaginación no tiene que tener límites.",
    "Atrévete a pensar en grande.",
    "Nunca tengas miedo de querer más para tu vida.",
    "Persigue aquello que realmente te apasiona.",
    "Haz algo que te haga sentir orgulloso de ti mismo.",
    "No vivas intentando complacer a todo el mundo.",
    "Tu vida es tu historia, no la de los demás.",
    "Aprende a decir no sin sentir culpa.",
    "Tu tranquilidad también es importante.",
    "Proteger tu paz no es egoísmo.",
    "Elegirte a ti mismo también es necesario.",
    "No necesitas demostrar tu valor constantemente.",
    "Quien te aprecia verá tu valor.",
    "Las personas correctas no te harán sentir insuficiente.",
    "Nunca mendigues atención.",
    "El amor verdadero no debería sentirse como una obligación.",
    "El respeto siempre debe estar presente.",
    "Una relación sana comienza con respeto.",
    "Ama sin perderte a ti mismo.",
    "No olvides quién eres por alguien más.",
    "El amor empieza también por uno mismo.",
    "Aprende a disfrutar de tu propia compañía.",
    "Estar solo no significa estar vacío.",
    "La soledad también puede ayudarte a conocerte.",
    "Conócete antes de buscar que otros te entiendan.",
    "Tu paz interior no tiene precio.",
    "Cuida tu mente como cuidas tu cuerpo.",
    "Descansar no significa rendirse.",
    "Está bien no estar bien todos los días.",
    "No tienes que ser fuerte todo el tiempo.",
    "Pedir ayuda también es valentía.",
    "Hablar de lo que sientes puede aliviar tu corazón.",
    "No guardes todo dentro de ti.",
    "Date permiso para comenzar de nuevo.",
    "Sé amable contigo cuando cometas errores.",
    "No te castigues por no saber algo que estás aprendiendo.",
    "Todos somos principiantes alguna vez.",
    "Aprender requiere paciencia.",
    "Cada error puede convertirse en experiencia.",
    "Nunca dejes de aprender.",
    "La curiosidad mantiene joven la mente.",
    "Pregunta, aprende y vuelve a intentarlo.",
    "El conocimiento nunca ocupa espacio de más.",
    "La experiencia llega cuando te atreves a intentar.",
    "No existe crecimiento sin salir de la zona cómoda.",
    "Los retos nos hacen descubrir de qué estamos hechos.",
    "Aquello que te desafía también puede hacerte crecer.",
    "No huyas siempre de lo difícil.",
    "A veces lo difícil es exactamente lo que necesitas.",
    "La comodidad no siempre significa felicidad.",
    "Atrévete a hacer algo nuevo.",
    "Cada aventura comienza con una decisión.",
    "La vida está hecha de momentos, no de cosas.",
    "Colecciona recuerdos, no solamente objetos.",
    "Disfruta el presente mientras construyes el futuro.",
    "No olvides vivir mientras persigues tus metas.",
    "El presente es el único momento que realmente tienes.",
    "Disfruta las pequeñas victorias.",
    "Celebra tus avances, aunque nadie más los vea.",
    "Cada pequeño logro merece reconocimiento.",
    "No minimices todo lo que has superado.",
    "Mira cuánto has avanzado.",
    "Has sobrevivido a días que pensaste que no superarías.",
    "Eres más fuerte de lo que crees.",
    "A veces necesitas recordar todo lo que ya lograste.",
    "No olvides darte crédito.",
    "Tu progreso merece ser celebrado.",
    "No te compares con quien empezó antes que tú.",
    "Cada persona tiene su propio ritmo.",
    "No existe una edad correcta para alcanzar tus sueños.",
    "Nunca es demasiado pronto ni demasiado tarde.",
    "Tu tiempo llegará.",
    "La paciencia también es parte del camino.",
    "No apresures aquello que necesita tiempo.",
    "Algunas cosas buenas requieren espera.",
    "La perseverancia convierte los sueños en metas.",
    "Una meta sin acción es solamente un deseo.",
    "Divide tus grandes metas en pequeños pasos.",
    "Haz una cosa cada día que te acerque a tu objetivo.",
    "La consistencia crea resultados.",
    "No necesitas hacerlo perfecto; necesitas hacerlo.",
    "Es mejor avanzar imperfectamente que esperar la perfección.",
    "La acción vence a la duda.",
    "Comienza antes de sentirte preparado.",
    "Nunca estarás completamente preparado para todo.",
    "El valor aparece cuando decides avanzar a pesar del miedo.",
    "No dejes que el miedo decida por ti.",
    "Atrévete a fallar.",
    "El fracaso no es el final.",
    "Cada intento te acerca un poco más.",
    "Si no funciona, aprende y vuelve a intentarlo.",
    "Cambiar de estrategia no significa abandonar.",
    "A veces necesitas otro camino para llegar al mismo destino.",
    "La flexibilidad también es fortaleza.",
    "Aprende a adaptarte sin perder tu esencia.",
    "Mantén tus valores incluso cuando cambien las circunstancias.",
    "Sé fiel a quien quieres ser.",
    "Tu esencia vale más que cualquier aprobación.",
    "No cambies para encajar donde no perteneces.",
    "Las personas correctas apreciarán tu autenticidad.",
    "Ser diferente también puede ser tu mayor fortaleza.",
    "No tengas miedo de destacar.",
    "Tu originalidad es parte de tu valor.",
    "No necesitas parecerte a nadie.",
    "Sé tú mismo con orgullo.",
    "La autenticidad atrae a las personas correctas.",
    "La verdadera confianza no necesita presumir.",
    "Habla menos de tus planes y trabaja más por ellos.",
    "Deja que tus resultados hablen.",
    "El trabajo constante siempre termina dejando huella.",
    "La paciencia y la disciplina forman una gran combinación.",
    "No abandones por no ver resultados inmediatos.",
    "Las raíces crecen antes de que aparezcan los frutos.",
    "Todo crecimiento necesita tiempo.",
    "Confía en las semillas que estás plantando hoy.",
    "Algún día agradecerás no haberte rendido.",
    "Sigue adelante, incluso si el camino parece lento.",
    "Un paso más puede cambiarlo todo.",
    "Nunca sabes qué hay después del próximo intento.",
    "La próxima oportunidad puede estar más cerca de lo que imaginas.",
    "Mantén los ojos abiertos para las nuevas posibilidades.",
    "La vida puede sorprenderte cuando menos lo esperas.",
    "No cierres la puerta antes de conocer lo que hay detrás.",
    "Cada día puede traer una nueva historia.",
    "Tu historia merece un final feliz, pero todavía la estás escribiendo.",
    "Escribe una vida de la que puedas sentirte orgulloso.",
    "Haz que tu futuro yo esté orgulloso de tu presente.",
    "No desperdicies tu potencial.",
    "Dentro de ti hay más posibilidades de las que imaginas.",
    "Puedes aprender aquello que todavía no sabes.",
    "Puedes mejorar aquello que todavía no dominas.",
    "Puedes comenzar aunque nadie te acompañe.",
    "Puedes volver a intentarlo aunque hayas fallado.",
    "Puedes cambiar tu historia desde hoy.",
    "Nunca subestimes el poder de una decisión.",
    "Una decisión puede cambiar un destino.",
    "Los grandes cambios empiezan con pequeñas decisiones.",
    "Hoy puede ser el comienzo de algo increíble.",
    "Haz que este día tenga un significado.",
    "Busca una razón para sonreír.",
    "La vida también merece momentos de diversión.",
    "No todo tiene que ser serio.",
    "Ríe más, preocúpate menos.",
    "Aprecia los momentos simples.",
    "Una buena conversación puede convertirse en un gran recuerdo.",
    "Los mejores recuerdos suelen ser inesperados.",
    "Disfruta de quienes hacen tus días mejores.",
    "Nunca sabes cuál será el último recuerdo de un momento.",
    "Valora el tiempo con las personas que quieres.",
    "Di lo que sientes antes de que sea demasiado tarde.",
    "Un pequeño gesto puede significar mucho.",
    "Nunca sabes cuánto puede ayudar una palabra amable.",
    "Sé la energía positiva que quieres encontrar.",
    "Haz que alguien sonría hoy.",
    "El mundo necesita más personas que hagan el bien.",
    "La amabilidad es gratis y puede valer muchísimo.",
    "Ayudar a alguien también puede ayudarte a ti.",
    "Nunca sabes qué batalla está enfrentando otra persona.",
    "Sé amable; todos estamos aprendiendo.",
    "Escucha antes de juzgar.",
    "Comprender es más importante que tener siempre la razón.",
    "No todas las discusiones necesitan ganarse.",
    "A veces la mejor respuesta es mantener la paz.",
    "El silencio también puede ser una respuesta.",
    "Aprende cuándo hablar y cuándo escuchar.",
    "No gastes energía en aquello que no puedes controlar.",
    "Concéntrate en lo que sí puedes cambiar.",
    "Tu energía es limitada; úsala sabiamente.",
    "No permitas que pequeños problemas roben grandes momentos.",
    "Elige tus batallas.",
    "Protege tu tiempo.",
    "Protege tu tranquilidad.",
    "Protege tus sueños.",
    "Protege tu corazón sin cerrarlo por completo.",
    "Sigue creyendo en las cosas buenas.",
    "La esperanza puede aparecer en los lugares más inesperados.",
    "Incluso una pequeña luz puede vencer mucha oscuridad.",
    "Después de los momentos difíciles, puedes descubrir una nueva fuerza.",
    "Tu pasado no tiene la última palabra.",
    "Tu presente puede cambiar tu futuro.",
    "Hoy tienes una nueva oportunidad para hacerlo diferente.",
    "Nunca sabes lo que puede suceder si decides intentarlo.",
    "Da el primer paso.",
    "Continúa con el segundo.",
    "Y cuando sea difícil, recuerda por qué comenzaste.",
    "No abandones tus sueños por un mal momento.",
    "Tu sueño merece una oportunidad.",
    "Haz que esa oportunidad sea hoy.",
    "El camino puede ser largo, pero cada paso cuenta.",
    "Sigue caminando.",
    "Sigue aprendiendo.",
    "Sigue creciendo.",
    "Sigue soñando.",
    "Sigue creyendo.",
    "Y sobre todo, sigue siendo tú."
];

function getRandomQuote() {
    return quotes[Math.floor(Math.random() * quotes.length)];
}

router.get('/', (req, res) => {
    try {
        const quote = getRandomQuote();

        res.json({
            status: true,
            creator: 'FamilyBot-MD',
            result: {
                quote
            }
        });
    } catch (error) {
        console.error('[QUOTE ERROR]', error);

        res.status(500).json({
            status: false,
            creator: 'FamilyBot-MD',
            message: 'No se pudo obtener una frase aleatoria.'
        });
    }
});

router.meta = {
    title: 'Frase aleatoria',
    description: 'Devuelve una frase motivacional al azar',
    icon: 'fas fa-quote-left',
    fields: [],
    resultType: 'text',
    resultField: 'quote'
};

module.exports = router;